logging:
  config: classpath:logback-spring.xml

# 日志是否打印sql
showSql: true

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.200.154:3306/luckysheet?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: jRoQ#BF%P4IN
    dbcp2:
      initial-size: 10
      min-idle: 10
      max-total: 1000
      # 配置获取连接等待超时的时间
      max-wait-millis: 6000000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
